const toggle=document.querySelector('.nav-toggle');const links=document.querySelector('.nav-links');
toggle?.addEventListener('click',()=>{links.classList.toggle('open');toggle.setAttribute('aria-expanded',links.classList.contains('open'))});
links?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>links.classList.remove('open')));

// Keep the Work Feed in the shared navigation, including older pages.
document.querySelectorAll('.nav-links').forEach(nav=>{if(!nav.querySelector('[href="work-feed.html"]')){const youtube=nav.querySelector('[href="youtube.html"]');const item=document.createElement('li');item.innerHTML='<a href="work-feed.html">Work Feed</a>';youtube?.parentElement?nav.insertBefore(item,youtube.parentElement):nav.appendChild(item)}});

// Add a Google YouTube Data API key here to automatically show the newest videos from all three channels.
const youtubeConfig={apiKey:null,handles:['letsfindways','DidarAhmadofficial','DidarAhmad_vlogs']};
async function loadLatestVideos(){const target=document.querySelector('[data-youtube-feed]');if(!target||!youtubeConfig.apiKey)return;try{const channels=await Promise.all(youtubeConfig.handles.map(async handle=>{const url=`https://www.googleapis.com/youtube/v3/channels?key=${youtubeConfig.apiKey}&forHandle=${handle}&part=id`;const data=await (await fetch(url)).json();return data.items?.[0]?.id}));const results=await Promise.all(channels.filter(Boolean).map(async channelId=>{const url=`https://www.googleapis.com/youtube/v3/search?key=${youtubeConfig.apiKey}&channelId=${channelId}&part=snippet,id&order=date&type=video&maxResults=3`;return (await (await fetch(url)).json()).items||[]}));const videos=results.flat().sort((a,b)=>new Date(b.snippet.publishedAt)-new Date(a.snippet.publishedAt)).slice(0,6);target.innerHTML=videos.map(video=>`<article class="video-card"><a href="https://www.youtube.com/watch?v=${video.id.videoId}" target="_blank" rel="noopener"><img class="video-thumb" src="${video.snippet.thumbnails.medium.url}" alt=""></a><div><p>${new Date(video.snippet.publishedAt).toLocaleDateString()}</p><h3>${video.snippet.title}</h3><a class="text-link" href="https://www.youtube.com/watch?v=${video.id.videoId}" target="_blank" rel="noopener">Watch video ↗</a></div></article>`).join('')}catch(error){console.warn('Unable to load YouTube videos.',error)}}
loadLatestVideos();
