(function(){const app=window.DidarWorkFeed;if(!app)return;const db=app.client;const escape=value=>String(value||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const videoId=url=>{try{const u=new URL(url);return u.searchParams.get('v')||u.pathname.split('/').filter(Boolean).pop()}catch{return ''}};const card=p=>`<article class="feed-card"><img src="${escape(p.thumbnail_url)||'images/project-website.png'}" alt="${escape(p.title)}"><div class="feed-card-body"><div class="feed-card-meta"><span>${escape(p.category||'Project')}</span><span>${new Date(p.published_at||p.created_at).toLocaleDateString()}</span></div><h3>${escape(p.title)}</h3><p>${escape(p.description||'Explore this project and its creative process.')}</p><div class="tag-list">${(p.tech_stack||[]).slice(0,4).map(x=>`<span>${escape(x)}</span>`).join('')}${p.featured?'<span class="featured">Featured</span>':''}</div><div class="card-actions"><a href="#" data-watch="${escape(p.youtube_url)}">Watch demo ↗</a>${p.website_url?`<a href="${escape(p.website_url)}" target="_blank" rel="noopener">Visit ↗</a>`:''}</div></div></article>`;
async function latest(){const target=document.querySelector('[data-latest-work]');if(!target)return;const {data,error}=await db.from('projects').select('*').eq('published',true).eq('show_on_homepage',true).order('featured',{ascending:false}).order('published_at',{ascending:false}).limit(3);target.innerHTML=error||!data?.length?'<p class="feed-empty">Featured work will appear here as soon as it is published.</p>':data.map(card).join('');bindWatch(target)}
async function feed(){const grid=document.querySelector('[data-work-feed]');if(!grid)return;let page=0;const per=9;const search=document.querySelector('[data-search]'),category=document.querySelector('[data-category]'),sort=document.querySelector('[data-sort]'),pages=document.querySelector('[data-pages]');async function load(){grid.innerHTML='<p class="feed-loading">Loading work…</p>';let q=db.from('projects').select('*',{count:'exact'}).eq('published',true).eq('display_in_feed',true);if(search.value)q=q.ilike('title',`%${search.value}%`);if(category.value)q=q.eq('category',category.value);if(sort.value==='oldest')q=q.order('published_at',{ascending:true});else if(sort.value==='featured')q=q.order('featured',{ascending:false}).order('published_at',{ascending:false});else q=q.order('published_at',{ascending:false});const {data,error,count}=await q.range(page*per,page*per+per-1);grid.innerHTML=error?`<p class="feed-empty">Unable to load work feed.</p>`:data?.length?data.map(card).join(''):'<p class="feed-empty">No projects match your search yet.</p>';bindWatch(grid);const total=Math.ceil((count||0)/per);pages.innerHTML=Array.from({length:total},(_,i)=>`<button class="${i===page?'active':''}" data-page="${i}">${i+1}</button>`).join('');pages.querySelectorAll('button').forEach(b=>b.onclick=()=>{page=Number(b.dataset.page);load();window.scrollTo({top:grid.offsetTop-100,behavior:'smooth'})})} [search,category,sort].forEach(x=>x.addEventListener('input',()=>{page=0;load()}));load()}
function bindWatch(scope){scope.querySelectorAll('[data-watch]').forEach(a=>a.onclick=e=>{e.preventDefault();const id=videoId(a.dataset.watch);if(id){document.querySelector('[data-video-frame]').src=`https://www.youtube-nocookie.com/embed/${id}?autoplay=1`;document.querySelector('[data-video-modal]').classList.add('open')}})}document.querySelector('[data-modal-close]')?.addEventListener('click',()=>{
    document.querySelector('[data-video-modal]').classList.remove('open');
    document.querySelector('[data-video-frame]').src='';
});

latest();
feed();

window.WorkFeedHelpers = {
    videoId,
    card,
    escape
};

})();
